### ISSUE TITLE
[Bug]: Installing on Forge results in java.lang.ClassNotFoundException: org.spongepowered.asm.synthetic.args.Args$1

### ISSUE THREAD

**Issue by fernanfs** [terrarium-earth/hercules#146]
### Bug Description

When adding Heracles to an (empty) forge installation, it crashes with the following stacktrace:

```
net.minecraft.ReportedException: Rendering overlay
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:961) ~[client-1.20.1-20230612.114412-srg.jar%23155!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146) ~[client-1.20.1-20230612.114412-srg.jar%23155!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23155!/:?]
	at net.minecraft.client.main.Main.main(Main.java:218) ~[1.20.1-1.20.1-47.2.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.1.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.2.1.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.2.1.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?]
Caused by: java.lang.RuntimeException: java.lang.NoClassDefFoundError: org/spongepowered/asm/synthetic/args/Args$1
	at net.minecraft.Util.m_137559_(Util.java:218) ~[client-1.20.1-20230612.114412-srg.jar%23155!/:?]
	at net.minecraft.client.Minecraft.m_91239_(Minecraft.java:664) ~[client-1.20.1-20230612.114412-srg.jar%23155!/:?]
	at net.minecraft.Util.m_137521_(Util.java:419) ~[client-1.20.1-20230612.114412-srg.jar%23155!/:?]
	at net.minecraft.client.Minecraft.lambda$new$5(Minecraft.java:564) ~[client-1.20.1-20230612.114412-srg.jar%23155!/:?]
	at net.minecraftforge.client.loading.ForgeLoadingOverlay.m_88315_(ForgeLoadingOverlay.java:148) ~[forge-1.20.1-47.2.1-universal.jar%23160!/:?]
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:954) ~[client-1.20.1-20230612.114412-srg.jar%23155!/:?]
	... 18 more
Caused by: java.lang.NoClassDefFoundError: org/spongepowered/asm/synthetic/args/Args$1
	at net.minecraft.client.gui.screens.TitleScreen.m_96763_(TitleScreen.java:158) ~[client-1.20.1-20230612.114412-srg.jar%23155!/:?]
	at net.minecraft.client.gui.screens.TitleScreen.m_7856_(TitleScreen.java:121) ~[client-1.20.1-20230612.114412-srg.jar%23155!/:?]
	at net.minecraft.client.gui.screens.Screen.m_6575_(Screen.java:321) ~[client-1.20.1-20230612.114412-srg.jar%23155!/:?]
	at net.minecraft.client.Minecraft.m_91152_(Minecraft.java:1007) ~[client-1.20.1-20230612.114412-srg.jar%23155!/:?]
	at net.minecraft.client.Minecraft.m_278684_(Minecraft.java:603) ~[client-1.20.1-20230612.114412-srg.jar%23155!/:?]
	at net.minecraft.client.Minecraft.lambda$new$4(Minecraft.java:583) ~[client-1.20.1-20230612.114412-srg.jar%23155!/:?]
	at net.minecraft.Util.m_137521_(Util.java:421) ~[client-1.20.1-20230612.114412-srg.jar%23155!/:?]

```

I've tried multiple version of forge, but all resulted in the very same exception.

This is a full logfile of my latest test. 
[latest.log](https://github.com/terrarium-earth/Heracles/files/13537399/latest.log)

### How to Reproduce?

1. Create an empty forge profile in the Modrinth App
2. Add Heracles as a dependency
3. Start and during startup it will crash

### Version

1.1.5

### Mod Loader Version

1.20.1-47.1.47, 1.20.1-47.2.1, 1.20.1-47.2.8

### Mod Loader

Forge

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by fernanfs** [comment]
It seems to be a problem related to the latest version only. The previous version 1.1.4 starts just fine

**Comment by Foozey** [comment]
Can confirm.
