### ISSUE TITLE
[Bug]: ConcurrentModificationException

### ISSUE THREAD

**Issue by LynxN1** [terrarium-earth/hercules#247]
### Bug Description

This error is crashing the server. In addition to Heracles, the server also has Argonauts and Handcrafted.

### Version

1.1.13

### Mod Loader Version

1.20.1 - 0.16.5

### Mod Loader

Fabric

### Logs or additional context
```
[23:05:30] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.class_148: Ticking entity
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:901) ~[server-intermediary.jar:?]
	at net.minecraft.class_3176.method_3813(class_3176.java:283) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1013) ~[?:?]
	at java.util.ArrayList$Itr.next(ArrayList.java:967) ~[?:?]
	at earth.terrarium.heracles.common.handlers.progress.QuestsProgress.testAndProgressTaskType(QuestsProgress.java:32) ~[Heracles-fabric-1.20.1-1.1.13.jar:?]
	at earth.terrarium.heracles.fabric.HeraclesFabric.lambda$init$1(HeraclesFabric.java:34) ~[Heracles-fabric-1.20.1-1.1.13.jar:?]
	at net.fabricmc.fabric.api.entity.event.v1.ServerEntityCombatEvents.lambda$static$0(ServerEntityCombatEvents.java:37) ~[fabric-entity-events-v1-1.6.0+1c78457f77-e3c453032de852de.jar:?]
	at net.minecraft.class_1309.wrapOperation$ckk000$fabric-entity-events-v1$onEntityKilledOther(class_1309.java:29178) ~[server-intermediary.jar:?]
	at net.minecraft.class_1309.method_6078(class_1309.java:1364) ~[server-intermediary.jar:?]
	at net.minecraft.class_1308.method_6078(class_1308.java:6154) ~[server-intermediary.jar:?]
	at net.minecraft.class_1309.method_5643(class_1309.java:1222) ~[server-intermediary.jar:?]
	at net.minecraft.class_1665.mixinextras$bridge$method_5643$86(class_1665.java) ~[server-intermediary.jar:?]
	at net.minecraft.class_1665.wrapOperation$gfc000$spell_engine$wrapDamageEntity(class_1665.java:5899) ~[server-intermediary.jar:?]
	at net.minecraft.class_1665.method_7454(class_1665.java:374) ~[server-intermediary.jar:?]
	at net.minecraft.class_1676.method_7488(class_1676.java:153) ~[server-intermediary.jar:?]
	at net.minecraft.class_1665.method_5773(class_1665.java:227) ~[server-intermediary.jar:?]
	at net.minecraft.class_1679.method_5773(class_1679.java:31) ~[server-intermediary.jar:?]
	at net.minecraft.class_3218.method_18762(class_3218.java:739) ~[server-intermediary.jar:?]
	at net.minecraft.class_1937.method_18472(class_1937.java:480) ~[server-intermediary.jar:?]
	at net.minecraft.class_3218.method_31420(class_3218.java:385) ~[server-intermediary.jar:?]
	at net.minecraft.class_5574.method_31791(class_5574.java:54) ~[server-intermediary.jar:?]
	at net.minecraft.class_3218.method_18765(class_3218.java:353) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897) ~[server-intermediary.jar:?]
	... 5 more
```
### Code of Conduct

- [x] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by ThatGravyBoat** [comment]
You have a mod that is executing something off thread it seems

**Comment by ledokua** [comment]
> You have a mod that is executing something off thread it seems

Sorry, but what you mean by that?

**Comment by SettingDust** [comment]
You have to find out the replicate

**Comment by ledokua** [comment]
Ok.
This happens sometimes when player have quest to kill mob and uses arrow to do this(any arrow)

**Comment by SettingDust** [comment]
Providing the mods. Minimal reproduce best.

**Comment by LynxN1** [comment]
[Crash report](https://pastebin.com/uvHGaYZa)
